# ---------------------------------------------------------------------------- #
#                    GENERAL PARTICLE SOURCE DEFAULT CONFIOG                   #
# ---------------------------------------------------------------------------- #

/gps/verbose 0
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1 
/gps/position 0 0 0 cm
/gps/direction 0 0 1


/gps/particle anti_proton 
/gps/ene/min 50 MeV
/gps/ene/max 250 MeV


# ---------------------------------------------------------------------------- #
#                    PARTICLE GUN FOR DEBUGGING MODE CONFIOG                   #
# ---------------------------------------------------------------------------- #


/NameOfFile/NameOfFile Prova

/run/initialize